// Adversarial RECALL tests for probeCompromisedPackages — round 1.
//
// Written from the shipped spec (src/learn/patterns/package-json-supply-chain.md)
// and the documented public threat-intel anchors. Deliberately NOT derived from
// the probe implementation, the threat-intel manifest, or any existing test.
//
// Anchors relied on (documented behavior):
//   axios 1.14.1 and 0.30.4 known-compromised; 1.7.2 clean
//   @tanstack/react-router 1.169.5 and 1.169.8 compromised; 1.169.9 clean
//   @bitwarden/cli 2026.4.0 compromised
//   plain-crypto-js compromised at EVERY version
//
// Documented probe behaviors under test:
//   - direct deps across dependencies / devDependencies / peerDependencies /
//     optionalDependencies / overrides / resolutions
//   - SemVer-aware range matching (ranges containing a bad version flag,
//     ranges excluding it do not)
//   - floating specs (latest / * / empty) on packages with a known-bad
//     version flag at high severity
//   - all-versions packages flag at critical for any spec
//   - transitive detection through package-lock.json (v7+ packages format and
//     legacy dependencies format), yarn.lock, pnpm-lock.yaml (v9), bun.lock,
//     with "(transitive via ...)" in the title

import { describe, it, expect } from 'vitest';
import { probeCompromisedPackages } from '../lib/probes.js';

const SEVERITIES = ['critical', 'high', 'medium', 'low', 'info'];

const manifest = (fields) =>
  JSON.stringify({ name: 'ledger-sync', version: '1.0.0', ...fields }, null, 2);

const one = (path, content) => [{ path, content }];

const scan = (files) => probeCompromisedPackages(files);

const hitsFor = (findings, pkgName) =>
  findings.filter(
    (f) =>
      (f.title && f.title.includes(pkgName)) || (f.evidence && String(f.evidence).includes(pkgName))
  );

// A lockfile scenario the spec pins: root package.json depends on a clean
// intermediate (left-util), which pulls in a compromised axios transitively.
const rootManifestWithIntermediate = manifest({
  dependencies: { 'left-util': '^2.0.0' },
});

const npmLockV3Transitive = JSON.stringify(
  {
    name: 'ledger-sync',
    version: '1.0.0',
    lockfileVersion: 3,
    requires: true,
    packages: {
      '': {
        name: 'ledger-sync',
        version: '1.0.0',
        dependencies: { 'left-util': '^2.0.0' },
      },
      'node_modules/left-util': {
        version: '2.0.1',
        resolved: 'https://registry.npmjs.org/left-util/-/left-util-2.0.1.tgz',
        integrity: 'sha512-mN2qWkT7pGb0aRuVfLc9yHdJ3sEnB1o',
        dependencies: { axios: '^1.14.0' },
      },
      'node_modules/axios': {
        version: '1.14.1',
        resolved: 'https://registry.npmjs.org/axios/-/axios-1.14.1.tgz',
        integrity: 'sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu',
      },
    },
  },
  null,
  2
);

const npmLockLegacyTransitive = JSON.stringify(
  {
    name: 'ledger-sync',
    version: '1.0.0',
    lockfileVersion: 1,
    requires: true,
    dependencies: {
      'left-util': {
        version: '2.0.1',
        resolved: 'https://registry.npmjs.org/left-util/-/left-util-2.0.1.tgz',
        integrity: 'sha512-mN2qWkT7pGb0aRuVfLc9yHdJ3sEnB1o',
        requires: { axios: '^1.14.0' },
      },
      axios: {
        version: '1.14.1',
        resolved: 'https://registry.npmjs.org/axios/-/axios-1.14.1.tgz',
        integrity: 'sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu',
      },
    },
  },
  null,
  2
);

const yarnLockTransitive = [
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
  '# yarn lockfile v1',
  '',
  'axios@^1.14.0:',
  '  version "1.14.1"',
  '  resolved "https://registry.yarnpkg.com/axios/-/axios-1.14.1.tgz#f3a21c09"',
  '  integrity sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu',
  '',
  'left-util@^2.0.0:',
  '  version "2.0.1"',
  '  resolved "https://registry.yarnpkg.com/left-util/-/left-util-2.0.1.tgz#0b7de114"',
  '  integrity sha512-mN2qWkT7pGb0aRuVfLc9yHdJ3sEnB1o',
  '  dependencies:',
  '    axios "^1.14.0"',
  '',
].join('\n');

const pnpmLockV9Transitive = [
  "lockfileVersion: '9.0'",
  '',
  'settings:',
  '  autoInstallPeers: true',
  '  excludeLinksFromLockfile: false',
  '',
  'importers:',
  '  .:',
  '    dependencies:',
  '      left-util:',
  '        specifier: ^2.0.0',
  '        version: 2.0.1',
  '',
  'packages:',
  '  axios@1.14.1:',
  '    resolution: {integrity: sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu}',
  '  left-util@2.0.1:',
  '    resolution: {integrity: sha512-mN2qWkT7pGb0aRuVfLc9yHdJ3sEnB1o}',
  '',
  'snapshots:',
  '  axios@1.14.1: {}',
  '  left-util@2.0.1:',
  '    dependencies:',
  '      axios: 1.14.1',
  '',
].join('\n');

const bunLockTransitive = JSON.stringify(
  {
    lockfileVersion: 1,
    workspaces: {
      '': {
        name: 'ledger-sync',
        dependencies: { 'left-util': '^2.0.0' },
      },
    },
    packages: {
      'left-util': [
        'left-util@2.0.1',
        '',
        { dependencies: { axios: '^1.14.0' } },
        'sha512-mN2qWkT7pGb0aRuVfLc9yHdJ3sEnB1o',
      ],
      axios: ['axios@1.14.1', '', {}, 'sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu'],
    },
  },
  null,
  2
);

describe('probeCompromisedPackages — direct dependency buckets', () => {
  it('flags a compromised exact pin in dependencies (axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '1.14.1' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a compromised exact pin in devDependencies (axios 0.30.4)', () => {
    const findings = scan(one('package.json', manifest({ devDependencies: { axios: '0.30.4' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a compromised exact pin in peerDependencies (@tanstack/react-router 1.169.5)', () => {
    const findings = scan(
      one('package.json', manifest({ peerDependencies: { '@tanstack/react-router': '1.169.5' } }))
    );
    expect(hitsFor(findings, '@tanstack/react-router').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a compromised exact pin in optionalDependencies (@tanstack/react-router 1.169.8)', () => {
    const findings = scan(
      one(
        'package.json',
        manifest({ optionalDependencies: { '@tanstack/react-router': '1.169.8' } })
      )
    );
    expect(hitsFor(findings, '@tanstack/react-router').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a compromised exact pin in overrides (@bitwarden/cli 2026.4.0)', () => {
    const findings = scan(
      one('package.json', manifest({ overrides: { '@bitwarden/cli': '2026.4.0' } }))
    );
    expect(hitsFor(findings, '@bitwarden/cli').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a compromised exact pin in resolutions (axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ resolutions: { axios: '1.14.1' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('attributes a direct-dependency hit to package.json', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '1.14.1' } })));
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('package.json');
  });
});

describe('probeCompromisedPackages — semver ranges that contain a compromised version must flag', () => {
  it('flags caret range ^1.14.0 (contains axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '^1.14.0' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags tilde range ~1.14.0 (contains axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '~1.14.0' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags wildcard patch range 1.14.x (contains axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '1.14.x' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags open-ended range >=1.14.0 (contains axios 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '>=1.14.0' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags compound range >=1.14.0 <1.15.0 (contains axios 1.14.1)', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { axios: '>=1.14.0 <1.15.0' } }))
    );
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags tilde range ~0.30.0 (contains axios 0.30.4)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '~0.30.0' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags a caret range anchored at a clean version when the range still reaches a bad one (^1.7.2 contains 1.14.1)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '^1.7.2' } })));
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  it('flags tilde range ~1.169.0 for @tanstack/react-router (contains 1.169.5 and 1.169.8)', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { '@tanstack/react-router': '~1.169.0' } }))
    );
    expect(hitsFor(findings, '@tanstack/react-router').length).toBeGreaterThanOrEqual(1);
  });
});

describe('probeCompromisedPackages — ranges and pins that exclude the compromised versions must not flag', () => {
  it('does not flag a clean exact pin (axios 1.7.2)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '1.7.2' } })));
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });

  it('does not flag tilde range ~1.7.2 (excludes 1.14.1 and 0.30.4)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '~1.7.2' } })));
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });

  it('does not flag wildcard patch range 1.7.x (excludes both bad axios versions)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '1.7.x' } })));
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });

  it('does not flag caret range ^0.29.0 (0.x caret excludes 0.30.4)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '^0.29.0' } })));
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });

  it('does not flag the patched exact pin @tanstack/react-router 1.169.9', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { '@tanstack/react-router': '1.169.9' } }))
    );
    expect(hitsFor(findings, '@tanstack/react-router')).toHaveLength(0);
  });

  it('does not flag caret range ^1.169.9 (floor above both bad @tanstack versions)', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { '@tanstack/react-router': '^1.169.9' } }))
    );
    expect(hitsFor(findings, '@tanstack/react-router')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — floating specs on packages with a known-bad version', () => {
  it('flags "latest" on axios at high severity', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: 'latest' } })));
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('high');
  });

  it('flags "*" on axios at high severity', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '*' } })));
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('high');
  });

  it('flags an empty spec on axios at high severity', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { axios: '' } })));
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('high');
  });

  it('flags "latest" on @bitwarden/cli (package with a known-bad version)', () => {
    const findings = scan(
      one('package.json', manifest({ devDependencies: { '@bitwarden/cli': 'latest' } }))
    );
    expect(hitsFor(findings, '@bitwarden/cli').length).toBeGreaterThanOrEqual(1);
  });

  // Spec scopes the floating-spec rule to "packages with a known-bad version".
  // react has no documented compromised version, so this probe stays silent
  // (the general floating-version warning belongs to the Package.json probe).
  it('does not flag "*" on a package with no known-bad versions (react)', () => {
    const findings = scan(one('package.json', manifest({ dependencies: { react: '*' } })));
    expect(hitsFor(findings, 'react')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — all-versions-compromised packages flag critical for any spec', () => {
  it('flags plain-crypto-js at an arbitrary exact pin as critical', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { 'plain-crypto-js': '2.4.1' } }))
    );
    const hits = hitsFor(findings, 'plain-crypto-js');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('critical');
  });

  it('flags plain-crypto-js under a caret range as critical', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { 'plain-crypto-js': '^5.0.0' } }))
    );
    const hits = hitsFor(findings, 'plain-crypto-js');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('critical');
  });

  it('flags plain-crypto-js at "latest" as critical', () => {
    const findings = scan(
      one('package.json', manifest({ dependencies: { 'plain-crypto-js': 'latest' } }))
    );
    const hits = hitsFor(findings, 'plain-crypto-js');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('critical');
  });

  it('flags plain-crypto-js in devDependencies with a wildcard spec as critical', () => {
    const findings = scan(
      one('package.json', manifest({ devDependencies: { 'plain-crypto-js': '*' } }))
    );
    const hits = hitsFor(findings, 'plain-crypto-js');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].severity).toBe('critical');
  });
});

describe('probeCompromisedPackages — package-lock.json v7+ packages format', () => {
  it('detects a transitive compromised version and marks it "(transitive via ...)" naming the chain', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'package-lock.json', content: npmLockV3Transitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].title).toMatch(/transitive via/i);
    expect(hits[0].title).toContain('left-util');
  });

  it('attributes the lockfile hit to package-lock.json', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'package-lock.json', content: npmLockV3Transitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('package-lock.json');
  });

  it('stays silent on a packages-format lockfile that resolved a clean version', () => {
    const cleanLock = JSON.stringify(
      {
        name: 'ledger-sync',
        version: '1.0.0',
        lockfileVersion: 3,
        packages: {
          '': { name: 'ledger-sync', version: '1.0.0', dependencies: { axios: '^1.7.0' } },
          'node_modules/axios': {
            version: '1.7.2',
            resolved: 'https://registry.npmjs.org/axios/-/axios-1.7.2.tgz',
            integrity: 'sha512-Kb7yEfPzR0dWnGtoJ9qLcVh',
          },
        },
      },
      null,
      2
    );
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.7.0' } }) },
      { path: 'package-lock.json', content: cleanLock },
    ]);
    // The lockfile pins 1.7.2 (clean); no compromised-version finding for it.
    const lockHits = hitsFor(findings, 'axios').filter((f) => f.file.includes('package-lock.json'));
    expect(lockHits).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — package-lock.json legacy dependencies format', () => {
  it('detects a transitive compromised version through the legacy format with the transitive marker', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'package-lock.json', content: npmLockLegacyTransitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].title).toMatch(/transitive via/i);
  });

  it('stays silent on a legacy-format lockfile with only clean resolved versions', () => {
    const cleanLegacy = JSON.stringify(
      {
        name: 'ledger-sync',
        version: '1.0.0',
        lockfileVersion: 1,
        requires: true,
        dependencies: {
          axios: {
            version: '1.7.2',
            resolved: 'https://registry.npmjs.org/axios/-/axios-1.7.2.tgz',
            integrity: 'sha512-Kb7yEfPzR0dWnGtoJ9qLcVh',
          },
        },
      },
      null,
      2
    );
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.7.0' } }) },
      { path: 'package-lock.json', content: cleanLegacy },
    ]);
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — yarn.lock', () => {
  it('detects a transitive compromised resolution in yarn.lock with the transitive marker', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'yarn.lock', content: yarnLockTransitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('yarn.lock');
    expect(hits[0].title).toMatch(/transitive via/i);
  });

  it('detects a compromised scoped-package resolution in yarn.lock', () => {
    const scopedYarnLock = [
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      '# yarn lockfile v1',
      '',
      '"@tanstack/react-router@^1.169.0":',
      '  version "1.169.5"',
      '  resolved "https://registry.yarnpkg.com/@tanstack/react-router/-/react-router-1.169.5.tgz#9ad02c17"',
      '  integrity sha512-Vt3mReQw8nJcJf07UbLkq2p',
      '',
    ].join('\n');
    const findings = scan([
      {
        path: 'package.json',
        content: manifest({ dependencies: { '@tanstack/react-router': '^1.169.0' } }),
      },
      { path: 'yarn.lock', content: scopedYarnLock },
    ]);
    expect(hitsFor(findings, '@tanstack/react-router').length).toBeGreaterThanOrEqual(1);
  });

  it('stays silent on a yarn.lock that resolved only clean versions', () => {
    const cleanYarnLock = [
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      '# yarn lockfile v1',
      '',
      'axios@^1.7.0:',
      '  version "1.7.2"',
      '  resolved "https://registry.yarnpkg.com/axios/-/axios-1.7.2.tgz#b1e2a904"',
      '  integrity sha512-Kb7yEfPzR0dWnGtoJ9qLcVh',
      '',
    ].join('\n');
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.7.0' } }) },
      { path: 'yarn.lock', content: cleanYarnLock },
    ]);
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — pnpm-lock.yaml v9', () => {
  it('detects a transitive compromised snapshot in pnpm-lock.yaml with the transitive marker', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'pnpm-lock.yaml', content: pnpmLockV9Transitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('pnpm-lock.yaml');
    expect(hits[0].title).toMatch(/transitive via/i);
  });

  it('stays silent on a pnpm-lock.yaml v9 with only clean versions', () => {
    const cleanPnpmLock = [
      "lockfileVersion: '9.0'",
      '',
      'importers:',
      '  .:',
      '    dependencies:',
      '      axios:',
      '        specifier: ^1.7.0',
      '        version: 1.7.2',
      '',
      'packages:',
      '  axios@1.7.2:',
      '    resolution: {integrity: sha512-Kb7yEfPzR0dWnGtoJ9qLcVh}',
      '',
      'snapshots:',
      '  axios@1.7.2: {}',
      '',
    ].join('\n');
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.7.0' } }) },
      { path: 'pnpm-lock.yaml', content: cleanPnpmLock },
    ]);
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — bun.lock', () => {
  it('detects a transitive compromised package in bun.lock with the transitive marker', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'bun.lock', content: bunLockTransitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('bun.lock');
    expect(hits[0].title).toMatch(/transitive via/i);
  });

  it('stays silent on a bun.lock with only clean versions', () => {
    const cleanBunLock = JSON.stringify(
      {
        lockfileVersion: 1,
        workspaces: {
          '': { name: 'ledger-sync', dependencies: { axios: '^1.7.0' } },
        },
        packages: {
          axios: ['axios@1.7.2', '', {}, 'sha512-Kb7yEfPzR0dWnGtoJ9qLcVh'],
        },
      },
      null,
      2
    );
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.7.0' } }) },
      { path: 'bun.lock', content: cleanBunLock },
    ]);
    expect(hitsFor(findings, 'axios')).toHaveLength(0);
  });
});

describe('probeCompromisedPackages — multi-file corpora', () => {
  it('flags compromised deps in both a root and a nested workspace package.json', () => {
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '1.14.1' } }) },
      {
        path: 'packages/api/package.json',
        content: manifest({
          dependencies: { '@tanstack/react-router': '1.169.8' },
        }),
      },
    ]);
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
    expect(hitsFor(findings, '@tanstack/react-router').length).toBeGreaterThanOrEqual(1);
  });

  it('preserves the nested manifest path on nested-manifest hits', () => {
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { react: '18.3.1' } }) },
      {
        path: 'packages/web/package.json',
        content: manifest({ dependencies: { axios: '1.14.1' } }),
      },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].file).toContain('packages/web/package.json');
  });

  it('flags a lockfile-only transitive hit when the manifest itself is clean', () => {
    const findings = scan([
      { path: 'package.json', content: rootManifestWithIntermediate },
      { path: 'package-lock.json', content: npmLockV3Transitive },
    ]);
    const hits = hitsFor(findings, 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    for (const hit of hits) {
      expect(hit.file).not.toBe('package.json');
    }
  });

  it('reports a direct manifest hit without the transitive marker when both manifest and lockfile are present', () => {
    const directLock = JSON.stringify(
      {
        name: 'ledger-sync',
        version: '1.0.0',
        lockfileVersion: 3,
        packages: {
          '': { name: 'ledger-sync', version: '1.0.0', dependencies: { axios: '^1.14.0' } },
          'node_modules/axios': {
            version: '1.14.1',
            resolved: 'https://registry.npmjs.org/axios/-/axios-1.14.1.tgz',
            integrity: 'sha512-Qm4rGtvKn3rrJ9wLB0aU7qhVbFtvKeBKZu',
          },
        },
      },
      null,
      2
    );
    const findings = scan([
      { path: 'package.json', content: manifest({ dependencies: { axios: '^1.14.0' } }) },
      { path: 'package-lock.json', content: directLock },
    ]);
    const manifestHits = hitsFor(findings, 'axios').filter((f) => f.file.includes('package.json'));
    expect(manifestHits.length).toBeGreaterThanOrEqual(1);
    // Direct hits are not transitive; the transitive marker belongs to chain hits only.
    expect(manifestHits[0].title).not.toMatch(/transitive via/i);
  });
});

describe('probeCompromisedPackages — finding structure', () => {
  const directFindings = () =>
    scan(one('package.json', manifest({ dependencies: { axios: '1.14.1' } })));

  it('stamps every finding with probe "Compromised Packages"', () => {
    const findings = directFindings();
    expect(findings.length).toBeGreaterThanOrEqual(1);
    for (const f of findings) {
      expect(f.probe).toBe('Compromised Packages');
    }
  });

  it('uses a recognized severity, and treats a known-compromised exact pin as critical or high', () => {
    const hits = hitsFor(directFindings(), 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    for (const f of hits) {
      expect(SEVERITIES).toContain(f.severity);
    }
    expect(['critical', 'high']).toContain(hits[0].severity);
  });

  it('names the package and the flagged version in the title of a direct exact-pin hit', () => {
    const hits = hitsFor(directFindings(), 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(hits[0].title).toContain('axios');
    expect(hits[0].title).toContain('1.14.1');
  });

  it('carries non-empty id, category, cwe, evidence, and remediation fields', () => {
    const hits = hitsFor(directFindings(), 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    const f = hits[0];
    expect(typeof f.id).toBe('string');
    expect(f.id.length).toBeGreaterThan(0);
    expect(typeof f.category).toBe('string');
    expect(f.category.length).toBeGreaterThan(0);
    expect(typeof f.cwe).toBe('string');
    expect(f.cwe.length).toBeGreaterThan(0);
    expect(typeof f.evidence).toBe('string');
    expect(f.evidence.length).toBeGreaterThan(0);
    expect(typeof f.remediation).toBe('string');
    expect(f.remediation.length).toBeGreaterThan(0);
  });

  it('reports a usable line number for a direct hit', () => {
    const hits = hitsFor(directFindings(), 'axios');
    expect(hits.length).toBeGreaterThanOrEqual(1);
    expect(typeof hits[0].line).toBe('number');
    expect(hits[0].line).toBeGreaterThanOrEqual(1);
  });

  it('is deterministic: identical input produces identical findings (pure function)', () => {
    const files = one('package.json', manifest({ dependencies: { axios: '1.14.1' } }));
    const first = scan(files);
    const second = scan(files);
    expect(second).toEqual(first);
  });
});

describe('probeCompromisedPackages — clean corpora stay silent', () => {
  it('returns no findings for a manifest of clean pinned versions', () => {
    const findings = scan(
      one(
        'package.json',
        manifest({
          dependencies: { react: '18.3.1', 'react-dom': '18.3.1', axios: '1.7.2' },
          devDependencies: { vite: '5.4.11', '@tanstack/react-router': '1.169.9' },
        })
      )
    );
    expect(findings).toHaveLength(0);
  });

  it('returns no findings for a corpus with no manifest or lockfile at all', () => {
    const findings = scan([{ path: 'src/server.js', content: "import axios from 'axios';\n" }]);
    expect(findings).toHaveLength(0);
  });
});

describe('edge cases the spec does not pin down', () => {
  // The spec does not say whether the same compromised package listed in two
  // buckets yields one finding or two. It must yield at least one.
  it('flags a package that is compromised in both dependencies and devDependencies at least once', () => {
    const findings = scan(
      one(
        'package.json',
        manifest({
          dependencies: { axios: '1.14.1' },
          devDependencies: { axios: '1.14.1' },
        })
      )
    );
    expect(hitsFor(findings, 'axios').length).toBeGreaterThanOrEqual(1);
  });

  // The spec does not define behavior for unparseable manifests. A static
  // browser probe must at minimum not throw and must return an array.
  it('does not throw on a malformed package.json', () => {
    const broken = '{ "name": "ledger-sync", "dependencies": { "axios": "1.14.1", } }';
    let findings;
    expect(() => {
      findings = scan(one('package.json', broken));
    }).not.toThrow();
    expect(Array.isArray(findings)).toBe(true);
  });

  // npm alias specs ("npm:axios@1.14.1" under another name) are not covered
  // by the spec. Whatever the verdict, the probe must not crash on them.
  it('does not throw on an npm alias spec pointing at a compromised version', () => {
    let findings;
    expect(() => {
      findings = scan(
        one('package.json', manifest({ dependencies: { 'http-shim': 'npm:axios@1.14.1' } }))
      );
    }).not.toThrow();
    expect(Array.isArray(findings)).toBe(true);
  });

  // Prerelease-anchored ranges are not addressed by the spec. The probe must
  // at minimum survive them without throwing.
  it('does not throw on a prerelease-anchored range for a listed package', () => {
    let findings;
    expect(() => {
      findings = scan(one('package.json', manifest({ dependencies: { axios: '^1.14.0-beta.1' } })));
    }).not.toThrow();
    expect(Array.isArray(findings)).toBe(true);
  });
});
